### ISSUE TITLE
mask processing

### ISSUE THREAD

**Issue by RichardChangCA** [pietz/brats-segmentation#4]
Hello,

I do not understand why use these codes below for OT mask images, could you help me to illustrate it, please?

img[img == 4] = 1
img[img != 1] = 0

Why use img=4 not other numbers? is it related to T1c? I cannot find too much details about the dataset online, do you have some information about the dataset more detail?

Thanks!

**Comment by pietz** [comment]
It's been a while but I believe the segmentation masks are labeled using integer values for specific channels. In my example I only focus on one of them which is why I relabel them in binary form.
